# Generated by Django 6.0.4 on 2026-04-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.IntegerField(unique=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('lead', models.CharField(max_length=50)),
                ('employees', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(unique=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(max_length=20)),
                ('team', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.IntegerField(unique=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField(unique=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('lead', models.CharField(max_length=50)),
                ('employees', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='areamodel',
            name='email',
        ),
        migrations.AddField(
            model_name='areamodel',
            name='lead',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
