# Generated by Django 6.0.4 on 2026-05-01 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_structure', '0002_departmentmodel_employeemodel_rolemodel_teammodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodel',
            name='surname',
        ),
    ]
