# Generated by Django 6.0.4 on 2026-05-01 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_structure', '0003_remove_employeemodel_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areamodel',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='departmentmodel',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='teammodel',
            name='employees',
        ),
        migrations.AlterField(
            model_name='departmentmodel',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_structure.areamodel'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_structure.rolemodel'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_structure.teammodel'),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_structure.departmentmodel'),
        ),
    ]
