# Generated by Django 6.0.4 on 2026-05-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_structure', '0004_remove_areamodel_employees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmodel',
            name='area',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='role',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='team',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='department',
            field=models.CharField(max_length=50),
        ),
    ]
